/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/sos`; params?: Router.UnknownInputParams; } | { pathname: `/orbits/orbits`; params?: Router.UnknownInputParams; } | { pathname: `/orbits/crear-orbit`; params?: Router.UnknownInputParams; } | { pathname: `/orbits/orbit-inside`; params?: Router.UnknownInputParams; } | { pathname: `/user/change-password`; params?: Router.UnknownInputParams; } | { pathname: `/user/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/user/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/user/signup`; params?: Router.UnknownInputParams; } | { pathname: `/user/verify-code`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/sos`; params?: Router.UnknownOutputParams; } | { pathname: `/orbits/orbits`; params?: Router.UnknownOutputParams; } | { pathname: `/orbits/crear-orbit`; params?: Router.UnknownOutputParams; } | { pathname: `/orbits/orbit-inside`; params?: Router.UnknownOutputParams; } | { pathname: `/user/change-password`; params?: Router.UnknownOutputParams; } | { pathname: `/user/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/user/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/user/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/user/verify-code`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/navigation${`?${string}` | `#${string}` | ''}` | `/sos${`?${string}` | `#${string}` | ''}` | `/orbits/orbits${`?${string}` | `#${string}` | ''}` | `/orbits/crear-orbit${`?${string}` | `#${string}` | ''}` | `/orbits/orbit-inside${`?${string}` | `#${string}` | ''}` | `/user/change-password${`?${string}` | `#${string}` | ''}` | `/user/forgot-password${`?${string}` | `#${string}` | ''}` | `/user/perfil${`?${string}` | `#${string}` | ''}` | `/user/signup${`?${string}` | `#${string}` | ''}` | `/user/verify-code${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/sos`; params?: Router.UnknownInputParams; } | { pathname: `/orbits/orbits`; params?: Router.UnknownInputParams; } | { pathname: `/orbits/crear-orbit`; params?: Router.UnknownInputParams; } | { pathname: `/orbits/orbit-inside`; params?: Router.UnknownInputParams; } | { pathname: `/user/change-password`; params?: Router.UnknownInputParams; } | { pathname: `/user/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/user/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/user/signup`; params?: Router.UnknownInputParams; } | { pathname: `/user/verify-code`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
